### ISSUE TITLE
Programs runs in IDE,but gives error after being built.

### ISSUE THREAD

**Issue by EthNeural** [Glavo/MaterialFX-Java8#4]
### I am receiving this error and don't know what is causing this:

```
Exception in Application start method
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/ButtonSkin
        at io.github.palexdev.materialfx.controls.MFXButton.createDefaultSkin(MFXButton.java:351)
        at javafx.scene.control.Control.doProcessCSS(Control.java:897)
        at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
```

**Comment by Glavo** [comment]
> ### I am receiving this error and don't know what is causing this:
> ```
> Exception in Application start method
> Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/ButtonSkin
>         at io.github.palexdev.materialfx.controls.MFXButton.createDefaultSkin(MFXButton.java:351)
>         at javafx.scene.control.Control.doProcessCSS(Control.java:897)
>         at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
>         at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
>         at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
> ```

Did you package it into a shadowJar? 

This project supports both JavaFX 8 and JavaFX 9+ through multi-release jar. Please check whether the content of `META-INF/versions/9` in the final jar is preserved, and whether the `Multi-Release` entry in `META-INF/MANIFEST.MF` is `true`.
